-- =====================================================================================
-- 0175 — A shop remembers which device prints where
--
-- Printing is per DEVICE, not per shop. The counter iPad reaches a Bluetooth roll; the back-office
-- laptop has a USB printer and a driver; a seller's phone has neither and hands the receipt to an
-- app. One setting on the shop would be wrong on two of those three.
--
-- WHAT CAN SYNC AND WHAT CANNOT, because it shapes the table. A browser will not let a page keep a
-- USB or Bluetooth device handle: permission is granted to an origin for a device, and the handle is
-- re-acquired, never stored. So what syncs is the shop's CHOICE — this device prints over Bluetooth,
-- to a printer called "XP-58", on a 58mm roll — and the handle is re-acquired against that identity
-- when the page loads. `navigator.usb.getDevices()` and, in newer Chrome,
-- `navigator.bluetooth.getDevices()` return already-permitted devices with no prompt, so after the
-- first pairing the reconnect is invisible.
--
-- WHY ONLINE AT ALL, when the handle is local anyway. Three reasons, all of them things a shop
-- actually asked about:
--
--   · a phone that is lost or replaced is set up in one tap, because the shop already knows what
--     that counter prints to
--   · a shop can SEE what is configured where, rather than walking to each device to find out why
--     one of them prints and another does not
--   · the roll width belongs to the paper, not to the browser's local storage, and a receipt laid
--     out for 80mm and printed on 58mm loses its right-hand column silently
--
-- `device_id` is generated by the browser and kept in its own storage. It names a device without
-- identifying a person: a shop labels it ("Counter", "Ada's phone") and that label is the shop's
-- own word, not anything read off the hardware.
-- =====================================================================================

create table if not exists public.store_printers (
  id          uuid primary key default gen_random_uuid(),
  store_id    uuid not null references public.stores (id) on delete cascade,

  /**
   * WHICH DEVICE THIS IS, as the browser calls itself.
   *
   * Generated once by the browser and kept in its storage. Not derived from anything about the
   * hardware or the person: a fingerprint would identify a seller across shops, and this only needs
   * to tell one counter from another.
   */
  device_id   text not null,
  /** What the shop calls it. Theirs to name — "Counter", "Ada's phone", "back office". */
  device_label text,

  /**
   * HOW THIS DEVICE REACHES A PRINTER.
   *
   *   bluetooth — Web Bluetooth, straight to the roll. Android and desktop Chrome.
   *   usb       — WebUSB, straight to the roll. Reconnects with no prompt at all.
   *   ios_app   — handed to a thermal-printing app by URL scheme, because iOS has no Web Bluetooth.
   *   browser   — the browser's own print dialog, which is right where there is a real driver.
   *
   * Open text with a check rather than an enum: adding a way to print should be a migration that
   * adds a value, not one that rewrites a type every reader depends on.
   */
  kind        text not null check (kind in ('bluetooth', 'usb', 'ios_app', 'browser')),

  /** What the chooser reported, so a screen can say "printing to XP-58" rather than "printing". */
  printer_name text,

  /**
   * The paper. Belongs to the printer, not to the browser.
   *
   * A receipt laid out for 80mm and sent to a 58mm roll loses its right-hand column — the amounts —
   * and nothing warns anybody, because the printer prints what it is given and wraps the rest.
   */
  width_mm    numeric not null default 80 check (width_mm between 30 and 120),

  /*
   * ENOUGH TO FIND THE DEVICE AGAIN WITHOUT ASKING.
   *
   * `navigator.usb.getDevices()` hands back already-permitted devices and they are identified by
   * vendor and product id. Bluetooth devices carry an id that is stable per origin. Neither is a
   * handle and neither is any use to anybody else; they are how a page recognises the printer it was
   * already given permission for.
   */
  usb_vendor_id  integer,
  usb_product_id integer,
  bt_device_id   text,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- One printer per device per shop. A device that is set up again REPLACES what it said before
  -- rather than adding a second row nobody can choose between.
  unique (store_id, device_id)
);

create index if not exists store_printers_store_idx on public.store_printers (store_id);

alter table public.store_printers enable row level security;

/*
 * Readable by the shop, written only through the function below.
 *
 * A direct insert policy would let a browser write any `store_id` it liked. The writer checks
 * membership from `auth.uid()`, which is the rule everything else here follows.
 */
drop policy if exists store_printers_read on public.store_printers;
create policy store_printers_read on public.store_printers
  for select to authenticated using (public.is_store_member(store_id));

drop policy if exists store_printers_write on public.store_printers;
create policy store_printers_write on public.store_printers
  for all to authenticated using (false) with check (false);

drop trigger if exists touch_updated_at on public.store_printers;
create trigger touch_updated_at before update on public.store_printers
  for each row execute function public.tg_touch_updated_at();


/*
 * ─── WHAT THIS DEVICE PRINTS TO ────────────────────────────────────────────────────
 *
 * Saved against the caller's shop, read from `auth.uid()`. No permission code beyond membership:
 * choosing which printer the phone in your hand uses is not an administrative act, and gating it
 * behind `store.settings` would mean a seller cannot set up the till they are standing at.
 */
create or replace function public.set_my_printer(
  p_store_id      uuid,
  p_device_id     text,
  p_kind          text,
  p_device_label  text default null,
  p_printer_name  text default null,
  p_width_mm      numeric default 80,
  p_usb_vendor_id integer default null,
  p_usb_product_id integer default null,
  p_bt_device_id  text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_id uuid;
begin
  if not public.is_store_member(p_store_id) then
    raise exception 'that shop is not yours' using errcode = '42501';
  end if;
  if coalesce(btrim(p_device_id), '') = '' then
    raise exception 'a device has to say which device it is' using errcode = '22023';
  end if;

  insert into public.store_printers (
    store_id, device_id, device_label, kind, printer_name, width_mm,
    usb_vendor_id, usb_product_id, bt_device_id
  )
  values (
    p_store_id, btrim(p_device_id), nullif(btrim(coalesce(p_device_label, '')), ''), p_kind,
    nullif(btrim(coalesce(p_printer_name, '')), ''), coalesce(p_width_mm, 80),
    p_usb_vendor_id, p_usb_product_id, nullif(btrim(coalesce(p_bt_device_id, '')), '')
  )
  on conflict (store_id, device_id) do update
    set kind           = excluded.kind,
        -- A label the shop already gave this device is kept when the printer is changed: renaming
        -- the counter is a separate decision from re-pairing it.
        device_label   = coalesce(excluded.device_label, public.store_printers.device_label),
        printer_name   = excluded.printer_name,
        width_mm       = excluded.width_mm,
        usb_vendor_id  = excluded.usb_vendor_id,
        usb_product_id = excluded.usb_product_id,
        bt_device_id   = excluded.bt_device_id,
        updated_at     = now()
  returning id into v_id;

  return v_id;
end;
$$;

grant execute on function public.set_my_printer(uuid, text, text, text, text, numeric, integer, integer, text) to authenticated;


/* And forgetting one, for a device that is being handed on or a printer that has gone. */
create or replace function public.forget_my_printer(p_store_id uuid, p_device_id text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_store_member(p_store_id) then
    raise exception 'that shop is not yours' using errcode = '42501';
  end if;
  delete from public.store_printers
   where store_id = p_store_id and device_id = btrim(p_device_id);
end;
$$;

grant execute on function public.forget_my_printer(uuid, text) to authenticated;


/*
 * Every device the shop has set up, so Settings can show what prints where.
 *
 * The whole list, not just this device: "why does the counter print and my phone not" is answered by
 * seeing both, and a shop replacing a phone needs to see what the old one was set to.
 */
create or replace function public.my_printers(p_store_id uuid)
returns table (
  device_id    text,
  device_label text,
  kind         text,
  printer_name text,
  width_mm     numeric,
  usb_vendor_id integer,
  usb_product_id integer,
  bt_device_id text,
  updated_at   timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select sp.device_id, sp.device_label, sp.kind, sp.printer_name, sp.width_mm,
         sp.usb_vendor_id, sp.usb_product_id, sp.bt_device_id, sp.updated_at
    from public.store_printers sp
   where sp.store_id = p_store_id
     and public.is_store_member(p_store_id)
   order by sp.updated_at desc;
$$;

grant execute on function public.my_printers(uuid) to authenticated;

comment on table public.store_printers is
  'How each device reaches a printer. The CHOICE syncs; the browser''s device handle cannot and is re-acquired against the identity stored here.';
